SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbperf].[vw_innocuous_wait_types]') AND type in (N'V'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE VIEW [dbperf].[vw_innocuous_wait_types] AS Select 1 as A' 

END
GO


ALTER VIEW [dbperf].[vw_innocuous_wait_types]
AS

/****************************************************************
 *
 * NAME: dbperf.vw_innocuous_wait_types   
 *
 * PURPOSE:  Filter wait types based on recommendations from sqlskills, Paul S. Randal.
 *
 * DESCRIPTION: 
 *
 * AUTHOR:  
 * CREATED:  
 *
 *
 *****************************************************************/


	SELECT N'BROKER_EVENTHANDLER' as wait_type 
	   UNION 
	SELECT N'BROKER_RECEIVE_WAITFOR' 
		UNION 
	SELECT N'BROKER_TASK_STOP' 
		UNION 
	SELECT N'BROKER_TO_FLUSH' 
		UNION 
	SELECT N'BROKER_TRANSMITTER' 
		UNION 
	SELECT N'CHECKPOINT_QUEUE' 
		UNION 
	SELECT N'CHKPT' 
		UNION 
	SELECT N'CLR_AUTO_EVENT' 
		UNION 
	SELECT N'CLR_MANUAL_EVENT' 
		UNION 
	SELECT N'CLR_SEMAPHORE' 
		UNION 
	SELECT N'DBMIRROR_DBM_EVENT' 
		UNION 
	SELECT N'DBMIRROR_EVENTS_QUEUE' 
		UNION 
	SELECT N'DBMIRROR_WORKER_QUEUE' 
		UNION 
	SELECT N'DBMIRRORING_CMD' 
		UNION 
	SELECT N'DIRTY_PAGE_POLL' 
		UNION 
	SELECT N'DISPATCHER_QUEUE_SEMAPHORE' 
		UNION 
	SELECT N'EXECSYNC' 
		UNION 
	SELECT N'FSAGENT' 
		UNION 
	SELECT N'FT_IFTS_SCHEDULER_IDLE_WAIT' 
		UNION 
	SELECT N'FT_IFTSHC_MUTEX' 
		UNION 
	SELECT N'HADR_CLUSAPI_CALL' 
		UNION 
	SELECT N'HADR_FILESTREAM_IOMGR_IOCOMPLETIOSELECT N' 
		UNION 
	SELECT N'HADR_LOGCAPTURE_WAIT' 
		UNION 
	SELECT N'HADR_NOTIFICATION_DEQUEUE' 
		UNION 
	SELECT N'HADR_TIMER_TASK' 
		UNION 
	SELECT N'HADR_WORK_QUEUE' 
		UNION 
	SELECT N'KSOURCE_WAKEUP' 
		UNION 
	SELECT N'LAZYWRITER_SLEEP' 
		UNION 
	SELECT N'LOGMGR_QUEUE' 
		UNION 
	SELECT N'MEMORY_ALLOCATION_EXT' 
		UNION 
	SELECT N'ONDEMAND_TASK_QUEUE' 
		UNION 
	SELECT N'PARALLEL_REDO_DRAIN_WORKER' 
		UNION 
	SELECT N'PARALLEL_REDO_LOG_CACHE' 
		UNION 
	SELECT N'PARALLEL_REDO_TRAN_LIST' 
		UNION 
	SELECT N'PARALLEL_REDO_WORKER_SYNC' 
		UNION 
	SELECT N'PARALLEL_REDO_WORKER_WAIT_WORK' 
		UNION 
	SELECT N'PREEMPTIVE_OS_FLUSHFILEBUFFERS' 
		UNION 
	SELECT N'PREEMPTIVE_XE_GETTARGETSTATE' 
		UNION 
	SELECT N'PVS_PREALLOCATE' 
		UNION 
	SELECT N'PWAIT_ALL_COMPONENTS_INITIALIZED' 
		UNION 
	SELECT N'PWAIT_DIRECTLOGCONSUMER_GETNEXT' 
		UNION 
	SELECT N'PWAIT_EXTENSIBILITY_CLEANUP_TASK' 
		UNION 
	SELECT N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP' 
		UNION 
	SELECT N'QDS_ASYNC_QUEUE' 
		UNION 
	SELECT N'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP' 
		UNION
	SELECT N'QDS_SHUTDOWN_QUEUE' 
		UNION 
	SELECT N'REDO_THREAD_PENDING_WORK' 
		UNION 
	SELECT N'REQUEST_FOR_DEADLOCK_SEARCH' 
		UNION 
	SELECT N'RESOURCE_QUEUE' 
		UNION 
	SELECT N'SERVER_IDLE_CHECK' 
		UNION 
	SELECT N'SLEEP_BPOOL_FLUSH' 
		UNION 
	SELECT N'SLEEP_DBSTARTUP' 
		UNION 
	SELECT N'SLEEP_DCOMSTARTUP' 
		UNION 
	SELECT N'SLEEP_MASTERDBREADY' 
		UNION 
	SELECT N'SLEEP_MASTERMDREADY' 
		UNION 
	SELECT N'SLEEP_MASTERUPGRADED' 
		UNION 
	SELECT N'SLEEP_MSDBSTARTUP' 
		UNION 
	SELECT N'SLEEP_SYSTEMTASK' 
		UNION
	SELECT N'SLEEP_TASK' 
		UNION 
	SELECT N'SLEEP_TEMPDBSTARTUP' 
		UNION 
	SELECT N'SNI_HTTP_ACCEPT' 
		UNION 
	SELECT N'SOS_WORK_DISPATCHER' 
		UNION 
	SELECT N'SP_SERVER_DIAGNOSTICS_SLEEP'
		UNION 
	SELECT N'SQLTRACE_BUFFER_FLUSH' 
		UNION 
	SELECT N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP' 
		UNION 
	SELECT N'SQLTRACE_WAIT_ENTRIES' 
		UNION 
	SELECT N'VDI_CLIENT_OTHER' 
		UNION 
	SELECT N'WAIT_FOR_RESULTS' 
		UNION 
	SELECT N'WAITFOR' 
		UNION 
	SELECT N'WAITFOR_TASKSHUTDOWSELECT N' 
		UNION 
	SELECT N'WAIT_XTP_RECOVERY' 
		UNION 
	SELECT N'WAIT_XTP_HOST_WAIT' 
		UNION 
	SELECT N'WAIT_XTP_OFFLINE_CKPT_NEW_LOG' 
		UNION 
	SELECT N'WAIT_XTP_CKPT_CLOSE' 
		UNION 
	SELECT N'XE_DISPATCHER_JOISELECT N' 
		UNION 
	SELECT N'XE_DISPATCHER_WAIT' 
		UNION 
	SELECT N'XE_TIMER_EVENT' 
		UNION
--- additions
	SELECT N'HADR_FABRIC_CALLBACK' 
		UNION
	SELECT N'HADR_FILESTREAM_IOMGR_IOCOMPLETION' 
		UNION
	SELECT N'HADR_WORK_QUEUE' 
		UNION
	SELECT N'MSQL_XP' 
		UNION
	SELECT N'PREEMPTIVE_HTTP_REQUEST' 
		UNION
	SELECT N'PREEMPTIVE_HTTP_REQUEST' 
		UNION
	SELECT N'PREEMPTIVE_ODBCOPS' 
		UNION
--SELECT N'PREEMPTIVE_OS_AUTHENTICATIONOPS' UNION
--SELECT N'PREEMPTIVE_OS_AUTHORIZATIONOPS' UNION
	SELECT N'PREEMPTIVE_OS_CLOSEHANDLE' 
		UNION
	SELECT N'PREEMPTIVE_OS_CRYPTACQUIRECONTEXT' 
		UNION
	SELECT N'PREEMPTIVE_OS_CRYPTOPS' 
		UNION
	SELECT N'PREEMPTIVE_OS_DELETESECURITYCONTEXT' 
		UNION
	SELECT N'PREEMPTIVE_OS_DISCONNECTNAMEDPIPE' 
		UNION
		SELECT N'PREEMPTIVE_OS_FINDFILE' 
		UNION
	SELECT N'PREEMPTIVE_OS_GETCOMPRESSEDFILESIZE' 
		UNION
	SELECT N'PREEMPTIVE_OS_GETPROCADDRESS' 
		UNION
	SELECT N'PREEMPTIVE_OS_GETQUEUEDCOMPLETIONSTATUS' 
		UNION
--SELECT N'PREEMPTIVE_OS_LOOKUPACCOUNTSID' UNION
	SELECT N'PREEMPTIVE_OS_QUERYREGISTRY' 
		UNION
	SELECT N'PREEMPTIVE_OS_REVERTTOSELF' 
		UNION
	SELECT N'PREEMPTIVE_RG_RESPONSEFROMSERVER' 
		UNION
	SELECT N'PREEMPTIVE_XE_CALLBACKEXECUTE' 
		UNION
	SELECT N'RBIO_AWAIT_RESPONSE' 
		UNION 
	SELECT N'RBIO_COMM_RETRY' 
		UNION
	 SELECT N'RESERVED_MEMORY_ALLOCATION_EXT' 
		UNION
	SELECT N'RESOURCE_GOVERNOR_IDLE' 
		UNION
	SELECT N'SNI_CONN_DUP' 
		UNION
	SELECT N'WINFAB_API_CALL' 
		UNION
	SELECT N'XE_LIVE_TARGET_TVF' 
		UNION
	SELECT N'SQP_STATS_REPORTING' 
		UNION
	SELECT N'HADR_NOTIFICATION_DEQUEUE' 



GO


